name: dev build Windows

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Install Visual C++ Build Tools
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile "vc_redist.x64.exe"
          .\vc_redist.x64.exe /install /quiet /norestart
          
      - name: Build package
        run: |
          python -m build

      # - name: Copy Redistributable DLLs
      #   run: |
      #     mkdir release_dlls
      #     cp "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Redist\MSVC\14.36.32532\x64\Microsoft.VC143.CRT\*.dll" release_dlls/
      #     # ... then include these DLLs in your final artifact
          
      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: dist/

  test-windows:
    runs-on: windows-latest
    needs: build-windows
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.14"

      - name: Add user bin to PATH on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          $userBinPath = "$env:USERPROFILE\.local\bin"
          Add-Content -Path $env:GITHUB_PATH -Value $userBinPath

      - name: Retrieve windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-dist
          path: dist

      - name: Install
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install dist/langevin-2025.11.23a2-cp314-cp314-win_amd64.whl

      - name: Check Python path
        shell: powershell
        run: python -c "import sys; print(sys.path)"
      - name: Check Python details
        run: |
          python --version
          where python
          pip list
      - name: Run version no. unit test
        run: python -m unittest discover tests -p "*langevin*"
      - name: Run all unit tests
        run: python -m unittest discover tests 
      - name: Run demo
        shell: powershell
        run: |
          # $userBinPath = "$env:USERPROFILE\.local\bin"
          # Add-Content -Path $env:GITHUB_PATH -Value $userBinPath
          python demos\dp_mixed.py

  #         # pip install pybind11 numpy jupyter ipython matplotlib pandas tqdm ffmpeg-python
  #         # pip install --no-index --find-links=D:\a\Langevin\Langevin\dist\ langevin
          