name: Upload Python Package to TestPyPI

# Consider switching to using
#   https://cibuildwheel.pypa.io/en/stable/ci-services/#

on:
  # release:
  #   types: [published]
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  build-macos-latest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          
      - name: Build package
        run: |
          python -m build
          
      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: macos-latest-dist
          path: dist/

  build-macos-14:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          
      - name: Build package
        run: |
          python -m build
          
      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: macos-14-dist
          path: dist/

  build-macos-15:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          
      - name: Build package
        run: |
          python -m build
          
      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: macos-15-dist
          path: dist/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build auditwheel
          
      - name: Build package
        run: |
          python -m build
          mv dist dist_tmp
          auditwheel repair dist_tmp/*.whl --wheel-dir dist
          rm -f dist/*-linux_x86_64.whl
          
      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: linux-dist
          path: dist/

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          
      - name: Build package
        run: |
          python -m build
          
      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: dist/

  publish-to-testpypi:
    runs-on: ubuntu-latest
    needs: [
      build-macos-14, 
      build-macos-15, 
      build-macos-latest, 
      build-linux,
      build-windows, 
    ]
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read # To checkout the repository

    steps:
      - name: Retrieve macos-14 artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-14-dist
          path: dist/
      - name: Retrieve macos-15 artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-15-dist
          path: dist/
      - name: Retrieve macos artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-latest-dist
          path: dist/
      - name: Retrieve linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-dist
          path: dist/
      - name: Retrieve windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-dist
          path: dist/
          
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  test-macos:
    runs-on: macos-latest
    needs: build-macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.14"

      - name: Add user bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Retrieve linux artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-latest-dist
          path: dist/

      - name: Install package
        run: |
          unzip /home/runner/Langevin/Langevin/dist/*.zip -d testing/
          python -m pip install testing/*.whl

      - name: Unit tests
        run: python -m unittest discover tests

  test-linux:
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.14"
          
      # - name: Create and activate virtual environment
      #   run: |
      #     python -m venv venv
      #     source venv/bin/activate

      - name: Add user bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          # source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          # python -m pip install build

      - name: Retrieve linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-dist
          path: dist/

      # - name: Build package
      #   run: |
      #     python -m build

      - name: Install package
        run: |
          unzip /home/runner/Langevin/Langevin/dist/*.zip -d testing/
          python -m pip install testing/*.whl

      - name: Unit tests
        run: python -m unittest discover tests

  test-windows:
    runs-on: windows-latest
    needs: build-windows
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.14"

      - name: Add user bin to PATH on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          $userBinPath = "$env:USERPROFILE\.local\bin"
          Add-Content -Path $env:GITHUB_PATH -Value $userBinPath

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        # python -m pip install build

      - name: Retrieve windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-dist
          path: dist/

      - name: Install package
        run: |
          unzip D:\a\Langevin\Langevin\dist\*.zip -d testing
          python -m pip install testing\*.whl

      - name: Unit tests
        run: python -m unittest discover tests

