name: Windows

on:
  # release:
  #   types: [published]
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Prepare MSVC
        uses: bus1/cabuild/action/msdevshell@v1
        with:
          architecture: x64
      - name: Install MSVC redistributable
        shell: powershell
        run: |
            # Example for installing Visual C++ Redistributable 2015-2022 x64
            Start-Process -FilePath "vc_redist.x64.exe" -ArgumentList "/install /quiet /norestart" -Wait

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install langevin
          # pip install --index https://test.pypi.org/simple/ --default-index https://pypi.org/simple/  langevin
      - name: Check Python path
        shell: powershell
        run: python -c "import sys; print(sys.path)"
      - name: Check Python details
        run: |
          python --version
          where python
          pip list

      - name: Run version no. unit test
        run: python -m unittest discover tests -p "*langevin*"
      - name: Run all unit tests
        run: python -m unittest discover tests 
      - name: Run demo
        shell: powershell
        run: |
          # $userBinPath = "$env:USERPROFILE\.local\bin"
          # Add-Content -Path $env:GITHUB_PATH -Value $userBinPath
          python demos\dp_mixed.py

