name: Windows

on:
  # release:
  #   types: [published]
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Prepare MSVC
        uses: bus1/cabuild/action/msdevshell@v1
        with:
          architecture: x64
      - name: Download and Install Visual C++ Redistributable
        run: |
          # Download the latest supported Visual C++ Redistributable (2015-2022)
          # You can find the direct download link on the official Microsoft website
          # For x64 systems, use the vc_redist.x64.exe
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile "vc_redist.x64.exe"
          .\vc_redist.x64.exe /install /quiet /norestart
        shell: powershell
                  
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install langevin
          # pip install --index https://test.pypi.org/simple/ --default-index https://pypi.org/simple/  langevin
      - name: Check Python path
        shell: powershell
        run: python -c "import sys; print(sys.path)"
      - name: Check Python details
        run: |
          python --version
          where python
          pip list
      - name: Check site-packages
        run: |
          dir C:\hostedtoolcache\windows\Python\3.14.0\x64\Lib\site-packages\langevin
          dir C:\hostedtoolcache\windows\Python\3.14.0\x64\Lib\site-packages\langevin\base
          dir C:\hostedtoolcache\windows\Python\3.14.0\x64\Lib\site-packages\langevin\dp

      - name: Run version no. unit test
        run: python -m unittest discover tests -p "*langevin*"
      - name: Run all unit tests
        run: python -m unittest discover tests 
      - name: Run demo
        shell: powershell
        run: |
          # $userBinPath = "$env:USERPROFILE\.local\bin"
          # Add-Content -Path $env:GITHUB_PATH -Value $userBinPath
          python demos\dp_mixed.py

